import AppProvider from '@/app/app-provider'
import { baseOpenGraph } from '@/app/shared-metadata'
import SlideSession from '@/components/slide-session'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import '@/styles/tailwind.css'

import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'

// import dynamic from 'next/dynamic'
import Footer from '@/components/common/Footer'
import Header from '@/components/common/Header'

//import { DrawerProvider } from '@/contexts/drawer/drawerProvider'
//import { ModalProvider } from '@/contexts/modal/modalProvider'

//React-redux
//import { Provider } from 'react-redux'
//import store from '../store'

const bePro = Be_Vietnam_Pro({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  openGraph: baseOpenGraph,
  description: 'Generated by create next app',
}

//import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
//const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${bePro.className} antialiased`}>
        <Toaster />

        {/*<QueryClientProvider client={queryClient}>*/}

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider>
            <div className="mx-auto min-h-screen max-w-[1200px]  bg-gray-200 text-black">
              <Header />

              <main className="bg-content content xs:p-[12px] md:p-[16px] min-h-svh">
                {children}
              </main>
            </div>
            <Footer />
            <SlideSession />
          </AppProvider>
        </ThemeProvider>

        {/*</QueryClientProvider>*/}
      </body>
    </html>
  )
}
